<div id="payment-errors" class="validation-advice" style="display:none;"></div>

<?php $code = $this->getMethodCode() ?>
<ul id="payment_form_<?php echo $code ?>" style="display:none;"
    class="buckaroo3extended_input form-list buckaroo-method">
    <fieldset class="form-group">
        <input type="hidden" aria-describedby="amount-addon" autocomplete="off" autofocus="" class="form-control input-block-level" id="amount" min="0.01" pattern="\d*(.\d\d)?" placeholder="Amount" step="0.01" value="0.01">
    </fieldset>
    <div id="set-up-apple-pay-button" class="apple-pay apple-pay-set-up-button apple-pay-set-up-button-black input-block-level d-none"></div>
    <div id="apple-pay-button" class="apple-pay input-block-level d-none"></div>
    <div id="apple-pay-wrapper" lang="en" class="apple-pay apple-pay-button apple-pay-button-black"></div>
</ul>